### ISSUE TITLE
have you heard of rotur? :3

### ISSUE THREAD

**Issue by ThePandaDever** [Thebloxers998/SyncLink#2]
hey, was looking at this and feels VERY similar to this other project: https://rotur.dev/ is this project related? 🤔

**Comment by BlockBoi19** [comment]
No, it's not related as this project extension is being worked on

However it was inspired by that

**Comment by BlockBoi19** [comment]
And ik what the rotur extension is

**Comment by ThePandaDever** [comment]
> No, it's not related as this project extension is being worked on
> 
> However it was inspired by that

are u saying rotur isnt being worked on? 💀

**Comment by BlockBoi19** [comment]
no

**Comment by BlockBoi19** [comment]
Idk what I'm trying to say
